### ISSUE TITLE
simple fork

### ISSUE THREAD

**Issue by arasabbasi** [fandogh/codemeli#1]
Hi,

I programmed a validator, too. But  mine is generic Javascript code. 

I gave you the credits for your citylist.json file, which i used as areacodes.js file

have fun

Aras

**Comment by arasabbasi** [comment]
I forgot to give you the link to mine:

https://github.com/arasabbasi/validateCodeMelli

**Comment by pi0** [comment]
Hi. Thanks for informing us about that fork. BTW what do you mean exactly about "generic Javascript code"?

**Comment by arasabbasi** [comment]
The code which i wrote should be full portable. So I didnt use any fancy javascript library like jquery or javascript engine like nodejs. By this, if somebody wants to port it to any engine or wants to combine it with a library, he can take the code and modify it for his needs.

**Comment by pi0** [comment]
But if look at the source code, there is no platform specific requirement like jquery or node, but just a pure **JS** function which works everywhere... Anyway my glad seeing your work on this :)

Best wishes.

**Comment by arasabbasi** [comment]
Exactly. Your work is good because it is a nodejs module. Mine is good because it is pure js. ;)

I just wanted to give you the props for the city codes ;).

Best Regards
Aras
